import React, { useState } from 'react';
import PropTypes from 'prop-types';
import { Alert, StyleSheet, Text } from 'react-native';
import { Entypo, AntDesign, Feather } from '@expo/vector-icons'; 
import { useActionSheet } from '@expo/react-native-action-sheet';
import useNetworkListener from 'src/hooks/useNetworkListener';
import TopBar from 'src/components/TopBar/TopBar';
import Badge from 'src/components/Badge/Badge';
import theme from 'src/common/theme';
import device from 'src/utils/device';
import Modal from 'src/components/Modal/Modal';

const ReviewTopBar = ({
  demo,
  logout,
  stopDemo,
  loadReviews,
  submissionQueue,
  submissionErrors,
}) => {

  const isInternetReachable = useNetworkListener();
  const { showActionSheetWithOptions } = useActionSheet();
  const [ modalOpen, setModalOpen ] = useState(false);

  const uploadCompleted = submissionQueue.length === 0;
  const uploadQueue = submissionQueue.length;
  const uploadErrors = submissionErrors.length;

  let badgeColor = null;
  if (uploadCompleted) badgeColor = theme.palette.green;
  if (uploadQueue > 0) badgeColor = 'rgba(0, 0, 0, .1)';
  if (uploadErrors > 0) badgeColor = theme.palette.red;
  
  let badgeIcon = null;
  if (uploadCompleted) badgeIcon = <AntDesign name="check" size={10} color="white" />;
  if (uploadQueue > 0) badgeIcon = <AntDesign name="arrowup" size={10} color="white" />;

  return (
    <>
      <TopBar
        style={styles.wrapper}
        centerText="Reviews"
        left={<Entypo name="menu" size={20} color="white" />}
        leftOnPress={() => {
          showActionSheetWithOptions({
            options: [
              'Cancel',
              'Refresh',
              'Logout',
            ],
            destructiveButtonIndex: 2,
          }, buttonIndex => {
            if (buttonIndex === 1) {
              if (device('web')) {
                if (confirm('Half completed reviews will be lost. Are you sure ?')) {
                  loadReviews()
                }
              }
              else {
                Alert.alert('Are you sure ?', 'Half completed reviews will be lost', [
                { text: 'Cancel', style: 'cancel' },
                { text: 'OK', onPress: () => loadReviews() },
              ])
              }
            }
            if (buttonIndex === 2) {
              if (demo) stopDemo();
              else logout();
            }
          })
        }}
        right={
          <>
            {!isInternetReachable && (
              <Badge
                style={{ marginRight: 6, backgroundColor: theme.palette.red }}
                icon={<Feather name="wifi-off" size={10} color="white" />}
              />
            )}
            <Badge
              style={{ backgroundColor: badgeColor }}
              text={(uploadQueue > 0) ? uploadQueue : null}
              icon={badgeIcon}
            />
          </>
        }
        rightOnPress={() => setModalOpen(true)}
      />
      <Modal
        visible={modalOpen}
        close={() => setModalOpen(false)}
      >
        <Text>
          Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Pellentesque habitant morbi tristique senectus et netus. Scelerisque fermentum dui faucibus in. Nisi porta lorem mollis aliquam ut porttitor leo. At lectus urna duis convallis convallis. Quis hendrerit dolor magna eget est lorem ipsum dolor. Vel pharetra vel turpis nunc. Ipsum dolor sit amet consectetur. Nam at lectus urna duis convallis convallis tellus. Elementum integer enim neque volutpat ac tincidunt vitae semper. Et ultrices neque ornare aenean euismod elementum nisi. Interdum posuere lorem ipsum dolor sit amet consectetur adipiscing. Mi in nulla posuere sollicitudin aliquam. Tincidunt vitae semper quis lectus nulla at volutpat diam ut. Arcu cursus vitae congue mauris rhoncus aenean vel elit. Ligula ullamcorper malesuada proin libero nunc consequat. Egestas sed tempus urna et. Scelerisque purus semper eget duis at. Ut sem nulla pharetra diam sit amet nisl suscipit.
          Ut eu sem integer vitae. Hendrerit dolor magna eget est. In ornare quam viverra orci sagittis eu volutpat odio facilisis. Ipsum consequat nisl vel pretium lectus. Cras tincidunt lobortis feugiat vivamus. Et molestie ac feugiat sed lectus vestibulum mattis. Augue lacus viverra vitae congue eu consequat. Sit amet volutpat consequat mauris nunc congue nisi vitae suscipit. Dignissim convallis aenean et tortor at risus. Orci porta non pulvinar neque laoreet suspendisse interdum consectetur. Nunc faucibus a pellentesque sit.
          Phasellus faucibus scelerisque eleifend donec pretium vulputate sapien nec. Arcu cursus euismod quis viverra nibh cras pulvinar. Blandit aliquam etiam erat velit scelerisque in dictum. At volutpat diam ut venenatis tellus in. Tempus imperdiet nulla malesuada pellentesque elit eget gravida cum. Lacus laoreet non curabitur gravida. A diam sollicitudin tempor id eu. Sapien et ligula ullamcorper malesuada proin. Fermentum leo vel orci porta non. Nulla posuere sollicitudin aliquam ultrices sagittis orci. Ligula ullamcorper malesuada proin libero nunc consequat. Consectetur adipiscing elit pellentesque habitant morbi. Tortor dignissim convallis aenean et tortor. Nulla facilisi cras fermentum odio eu feugiat. Amet dictum sit amet justo donec enim. Rhoncus mattis rhoncus urna neque viverra justo nec ultrices dui. Arcu cursus euismod quis viverra. Morbi blandit cursus risus at ultrices. Aliquet lectus proin nibh nisl condimentum. Integer vitae justo eget magna fermentum iaculis eu.
          Mattis enim ut tellus elementum sagittis. Pharetra convallis posuere morbi leo. Bibendum arcu vitae elementum curabitur vitae nunc sed velit. Mi tempus imperdiet nulla malesuada pellentesque. Vel facilisis volutpat est velit egestas dui id ornare. Maecenas sed enim ut sem. Eros in cursus turpis massa tincidunt dui ut ornare. Mi bibendum neque egestas congue quisque egestas diam in arcu. Sit amet venenatis urna cursus eget nunc scelerisque viverra mauris. Tortor dignissim convallis aenean et tortor at. Nisl pretium fusce id velit ut tortor pretium viverra. Nunc aliquet bibendum enim facilisis. Quis ipsum suspendisse ultrices gravida dictum fusce ut placerat. Dui sapien eget mi proin sed libero. Maecenas sed enim ut sem. Nulla facilisi nullam vehicula ipsum a arcu cursus vitae. Egestas sed sed risus pretium quam. Congue nisi vitae suscipit tellus. Risus viverra adipiscing at in tellus integer. Nisl vel pretium lectus quam id leo in vitae.
          Nisl suscipit adipiscing bibendum est ultricies integer quis auctor. Proin fermentum leo vel orci porta non pulvinar. Sed odio morbi quis commodo. Purus sit amet luctus venenatis lectus. Hac habitasse platea dictumst vestibulum. Consectetur libero id faucibus nisl tincidunt eget nullam non. Habitant morbi tristique senectus et netus et. Nisi vitae suscipit tellus mauris. Tristique sollicitudin nibh sit amet commodo nulla facilisi nullam. Diam vulputate ut pharetra sit amet aliquam id diam.
          Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Pellentesque habitant morbi tristique senectus et netus. Scelerisque fermentum dui faucibus in. Nisi porta lorem mollis aliquam ut porttitor leo. At lectus urna duis convallis convallis. Quis hendrerit dolor magna eget est lorem ipsum dolor. Vel pharetra vel turpis nunc. Ipsum dolor sit amet consectetur. Nam at lectus urna duis convallis convallis tellus. Elementum integer enim neque volutpat ac tincidunt vitae semper. Et ultrices neque ornare aenean euismod elementum nisi. Interdum posuere lorem ipsum dolor sit amet consectetur adipiscing. Mi in nulla posuere sollicitudin aliquam. Tincidunt vitae semper quis lectus nulla at volutpat diam ut. Arcu cursus vitae congue mauris rhoncus aenean vel elit. Ligula ullamcorper malesuada proin libero nunc consequat. Egestas sed tempus urna et. Scelerisque purus semper eget duis at. Ut sem nulla pharetra diam sit amet nisl suscipit.
          Ut eu sem integer vitae. Hendrerit dolor magna eget est. In ornare quam viverra orci sagittis eu volutpat odio facilisis. Ipsum consequat nisl vel pretium lectus. Cras tincidunt lobortis feugiat vivamus. Et molestie ac feugiat sed lectus vestibulum mattis. Augue lacus viverra vitae congue eu consequat. Sit amet volutpat consequat mauris nunc congue nisi vitae suscipit. Dignissim convallis aenean et tortor at risus. Orci porta non pulvinar neque laoreet suspendisse interdum consectetur. Nunc faucibus a pellentesque sit.
          Phasellus faucibus scelerisque eleifend donec pretium vulputate sapien nec. Arcu cursus euismod quis viverra nibh cras pulvinar. Blandit aliquam etiam erat velit scelerisque in dictum. At volutpat diam ut venenatis tellus in. Tempus imperdiet nulla malesuada pellentesque elit eget gravida cum. Lacus laoreet non curabitur gravida. A diam sollicitudin tempor id eu. Sapien et ligula ullamcorper malesuada proin. Fermentum leo vel orci porta non. Nulla posuere sollicitudin aliquam ultrices sagittis orci. Ligula ullamcorper malesuada proin libero nunc consequat. Consectetur adipiscing elit pellentesque habitant morbi. Tortor dignissim convallis aenean et tortor. Nulla facilisi cras fermentum odio eu feugiat. Amet dictum sit amet justo donec enim. Rhoncus mattis rhoncus urna neque viverra justo nec ultrices dui. Arcu cursus euismod quis viverra. Morbi blandit cursus risus at ultrices. Aliquet lectus proin nibh nisl condimentum. Integer vitae justo eget magna fermentum iaculis eu.
          Mattis enim ut tellus elementum sagittis. Pharetra convallis posuere morbi leo. Bibendum arcu vitae elementum curabitur vitae nunc sed velit. Mi tempus imperdiet nulla malesuada pellentesque. Vel facilisis volutpat est velit egestas dui id ornare. Maecenas sed enim ut sem. Eros in cursus turpis massa tincidunt dui ut ornare. Mi bibendum neque egestas congue quisque egestas diam in arcu. Sit amet venenatis urna cursus eget nunc scelerisque viverra mauris. Tortor dignissim convallis aenean et tortor at. Nisl pretium fusce id velit ut tortor pretium viverra. Nunc aliquet bibendum enim facilisis. Quis ipsum suspendisse ultrices gravida dictum fusce ut placerat. Dui sapien eget mi proin sed libero. Maecenas sed enim ut sem. Nulla facilisi nullam vehicula ipsum a arcu cursus vitae. Egestas sed sed risus pretium quam. Congue nisi vitae suscipit tellus. Risus viverra adipiscing at in tellus integer. Nisl vel pretium lectus quam id leo in vitae.
          Nisl suscipit adipiscing bibendum est ultricies integer quis auctor. Proin fermentum leo vel orci porta non pulvinar. Sed odio morbi quis commodo. Purus sit amet luctus venenatis lectus. Hac habitasse platea dictumst vestibulum. Consectetur libero id faucibus nisl tincidunt eget nullam non. Habitant morbi tristique senectus et netus et. Nisi vitae suscipit tellus mauris. Tristique sollicitudin nibh sit amet commodo nulla facilisi nullam. Diam vulputate ut pharetra sit amet aliquam id diam.
          Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Pellentesque habitant morbi tristique senectus et netus. Scelerisque fermentum dui faucibus in. Nisi porta lorem mollis aliquam ut porttitor leo. At lectus urna duis convallis convallis. Quis hendrerit dolor magna eget est lorem ipsum dolor. Vel pharetra vel turpis nunc. Ipsum dolor sit amet consectetur. Nam at lectus urna duis convallis convallis tellus. Elementum integer enim neque volutpat ac tincidunt vitae semper. Et ultrices neque ornare aenean euismod elementum nisi. Interdum posuere lorem ipsum dolor sit amet consectetur adipiscing. Mi in nulla posuere sollicitudin aliquam. Tincidunt vitae semper quis lectus nulla at volutpat diam ut. Arcu cursus vitae congue mauris rhoncus aenean vel elit. Ligula ullamcorper malesuada proin libero nunc consequat. Egestas sed tempus urna et. Scelerisque purus semper eget duis at. Ut sem nulla pharetra diam sit amet nisl suscipit.
          Ut eu sem integer vitae. Hendrerit dolor magna eget est. In ornare quam viverra orci sagittis eu volutpat odio facilisis. Ipsum consequat nisl vel pretium lectus. Cras tincidunt lobortis feugiat vivamus. Et molestie ac feugiat sed lectus vestibulum mattis. Augue lacus viverra vitae congue eu consequat. Sit amet volutpat consequat mauris nunc congue nisi vitae suscipit. Dignissim convallis aenean et tortor at risus. Orci porta non pulvinar neque laoreet suspendisse interdum consectetur. Nunc faucibus a pellentesque sit.
          Phasellus faucibus scelerisque eleifend donec pretium vulputate sapien nec. Arcu cursus euismod quis viverra nibh cras pulvinar. Blandit aliquam etiam erat velit scelerisque in dictum. At volutpat diam ut venenatis tellus in. Tempus imperdiet nulla malesuada pellentesque elit eget gravida cum. Lacus laoreet non curabitur gravida. A diam sollicitudin tempor id eu. Sapien et ligula ullamcorper malesuada proin. Fermentum leo vel orci porta non. Nulla posuere sollicitudin aliquam ultrices sagittis orci. Ligula ullamcorper malesuada proin libero nunc consequat. Consectetur adipiscing elit pellentesque habitant morbi. Tortor dignissim convallis aenean et tortor. Nulla facilisi cras fermentum odio eu feugiat. Amet dictum sit amet justo donec enim. Rhoncus mattis rhoncus urna neque viverra justo nec ultrices dui. Arcu cursus euismod quis viverra. Morbi blandit cursus risus at ultrices. Aliquet lectus proin nibh nisl condimentum. Integer vitae justo eget magna fermentum iaculis eu.
          Mattis enim ut tellus elementum sagittis. Pharetra convallis posuere morbi leo. Bibendum arcu vitae elementum curabitur vitae nunc sed velit. Mi tempus imperdiet nulla malesuada pellentesque. Vel facilisis volutpat est velit egestas dui id ornare. Maecenas sed enim ut sem. Eros in cursus turpis massa tincidunt dui ut ornare. Mi bibendum neque egestas congue quisque egestas diam in arcu. Sit amet venenatis urna cursus eget nunc scelerisque viverra mauris. Tortor dignissim convallis aenean et tortor at. Nisl pretium fusce id velit ut tortor pretium viverra. Nunc aliquet bibendum enim facilisis. Quis ipsum suspendisse ultrices gravida dictum fusce ut placerat. Dui sapien eget mi proin sed libero. Maecenas sed enim ut sem. Nulla facilisi nullam vehicula ipsum a arcu cursus vitae. Egestas sed sed risus pretium quam. Congue nisi vitae suscipit tellus. Risus viverra adipiscing at in tellus integer. Nisl vel pretium lectus quam id leo in vitae.
          Nisl suscipit adipiscing bibendum est ultricies integer quis auctor. Proin fermentum leo vel orci porta non pulvinar. Sed odio morbi quis commodo. Purus sit amet luctus venenatis lectus. Hac habitasse platea dictumst vestibulum. Consectetur libero id faucibus nisl tincidunt eget nullam non. Habitant morbi tristique senectus et netus et. Nisi vitae suscipit tellus mauris. Tristique sollicitudin nibh sit amet commodo nulla facilisi nullam. Diam vulputate ut pharetra sit amet aliquam id diam.
          Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Pellentesque habitant morbi tristique senectus et netus. Scelerisque fermentum dui faucibus in. Nisi porta lorem mollis aliquam ut porttitor leo. At lectus urna duis convallis convallis. Quis hendrerit dolor magna eget est lorem ipsum dolor. Vel pharetra vel turpis nunc. Ipsum dolor sit amet consectetur. Nam at lectus urna duis convallis convallis tellus. Elementum integer enim neque volutpat ac tincidunt vitae semper. Et ultrices neque ornare aenean euismod elementum nisi. Interdum posuere lorem ipsum dolor sit amet consectetur adipiscing. Mi in nulla posuere sollicitudin aliquam. Tincidunt vitae semper quis lectus nulla at volutpat diam ut. Arcu cursus vitae congue mauris rhoncus aenean vel elit. Ligula ullamcorper malesuada proin libero nunc consequat. Egestas sed tempus urna et. Scelerisque purus semper eget duis at. Ut sem nulla pharetra diam sit amet nisl suscipit.
          Ut eu sem integer vitae. Hendrerit dolor magna eget est. In ornare quam viverra orci sagittis eu volutpat odio facilisis. Ipsum consequat nisl vel pretium lectus. Cras tincidunt lobortis feugiat vivamus. Et molestie ac feugiat sed lectus vestibulum mattis. Augue lacus viverra vitae congue eu consequat. Sit amet volutpat consequat mauris nunc congue nisi vitae suscipit. Dignissim convallis aenean et tortor at risus. Orci porta non pulvinar neque laoreet suspendisse interdum consectetur. Nunc faucibus a pellentesque sit.
          Phasellus faucibus scelerisque eleifend donec pretium vulputate sapien nec. Arcu cursus euismod quis viverra nibh cras pulvinar. Blandit aliquam etiam erat velit scelerisque in dictum. At volutpat diam ut venenatis tellus in. Tempus imperdiet nulla malesuada pellentesque elit eget gravida cum. Lacus laoreet non curabitur gravida. A diam sollicitudin tempor id eu. Sapien et ligula ullamcorper malesuada proin. Fermentum leo vel orci porta non. Nulla posuere sollicitudin aliquam ultrices sagittis orci. Ligula ullamcorper malesuada proin libero nunc consequat. Consectetur adipiscing elit pellentesque habitant morbi. Tortor dignissim convallis aenean et tortor. Nulla facilisi cras fermentum odio eu feugiat. Amet dictum sit amet justo donec enim. Rhoncus mattis rhoncus urna neque viverra justo nec ultrices dui. Arcu cursus euismod quis viverra. Morbi blandit cursus risus at ultrices. Aliquet lectus proin nibh nisl condimentum. Integer vitae justo eget magna fermentum iaculis eu.
          Mattis enim ut tellus elementum sagittis. Pharetra convallis posuere morbi leo. Bibendum arcu vitae elementum curabitur vitae nunc sed velit. Mi tempus imperdiet nulla malesuada pellentesque. Vel facilisis volutpat est velit egestas dui id ornare. Maecenas sed enim ut sem. Eros in cursus turpis massa tincidunt dui ut ornare. Mi bibendum neque egestas congue quisque egestas diam in arcu. Sit amet venenatis urna cursus eget nunc scelerisque viverra mauris. Tortor dignissim convallis aenean et tortor at. Nisl pretium fusce id velit ut tortor pretium viverra. Nunc aliquet bibendum enim facilisis. Quis ipsum suspendisse ultrices gravida dictum fusce ut placerat. Dui sapien eget mi proin sed libero. Maecenas sed enim ut sem. Nulla facilisi nullam vehicula ipsum a arcu cursus vitae. Egestas sed sed risus pretium quam. Congue nisi vitae suscipit tellus. Risus viverra adipiscing at in tellus integer. Nisl vel pretium lectus quam id leo in vitae.
          Nisl suscipit adipiscing bibendum est ultricies integer quis auctor. Proin fermentum leo vel orci porta non pulvinar. Sed odio morbi quis commodo. Purus sit amet luctus venenatis lectus. Hac habitasse platea dictumst vestibulum. Consectetur libero id faucibus nisl tincidunt eget nullam non. Habitant morbi tristique senectus et netus et. Nisi vitae suscipit tellus mauris. Tristique sollicitudin nibh sit amet commodo nulla facilisi nullam. Diam vulputate ut pharetra sit amet aliquam id diam.
          Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Pellentesque habitant morbi tristique senectus et netus. Scelerisque fermentum dui faucibus in. Nisi porta lorem mollis aliquam ut porttitor leo. At lectus urna duis convallis convallis. Quis hendrerit dolor magna eget est lorem ipsum dolor. Vel pharetra vel turpis nunc. Ipsum dolor sit amet consectetur. Nam at lectus urna duis convallis convallis tellus. Elementum integer enim neque volutpat ac tincidunt vitae semper. Et ultrices neque ornare aenean euismod elementum nisi. Interdum posuere lorem ipsum dolor sit amet consectetur adipiscing. Mi in nulla posuere sollicitudin aliquam. Tincidunt vitae semper quis lectus nulla at volutpat diam ut. Arcu cursus vitae congue mauris rhoncus aenean vel elit. Ligula ullamcorper malesuada proin libero nunc consequat. Egestas sed tempus urna et. Scelerisque purus semper eget duis at. Ut sem nulla pharetra diam sit amet nisl suscipit.
          Ut eu sem integer vitae. Hendrerit dolor magna eget est. In ornare quam viverra orci sagittis eu volutpat odio facilisis. Ipsum consequat nisl vel pretium lectus. Cras tincidunt lobortis feugiat vivamus. Et molestie ac feugiat sed lectus vestibulum mattis. Augue lacus viverra vitae congue eu consequat. Sit amet volutpat consequat mauris nunc congue nisi vitae suscipit. Dignissim convallis aenean et tortor at risus. Orci porta non pulvinar neque laoreet suspendisse interdum consectetur. Nunc faucibus a pellentesque sit.
          Phasellus faucibus scelerisque eleifend donec pretium vulputate sapien nec. Arcu cursus euismod quis viverra nibh cras pulvinar. Blandit aliquam etiam erat velit scelerisque in dictum. At volutpat diam ut venenatis tellus in. Tempus imperdiet nulla malesuada pellentesque elit eget gravida cum. Lacus laoreet non curabitur gravida. A diam sollicitudin tempor id eu. Sapien et ligula ullamcorper malesuada proin. Fermentum leo vel orci porta non. Nulla posuere sollicitudin aliquam ultrices sagittis orci. Ligula ullamcorper malesuada proin libero nunc consequat. Consectetur adipiscing elit pellentesque habitant morbi. Tortor dignissim convallis aenean et tortor. Nulla facilisi cras fermentum odio eu feugiat. Amet dictum sit amet justo donec enim. Rhoncus mattis rhoncus urna neque viverra justo nec ultrices dui. Arcu cursus euismod quis viverra. Morbi blandit cursus risus at ultrices. Aliquet lectus proin nibh nisl condimentum. Integer vitae justo eget magna fermentum iaculis eu.
          Mattis enim ut tellus elementum sagittis. Pharetra convallis posuere morbi leo. Bibendum arcu vitae elementum curabitur vitae nunc sed velit. Mi tempus imperdiet nulla malesuada pellentesque. Vel facilisis volutpat est velit egestas dui id ornare. Maecenas sed enim ut sem. Eros in cursus turpis massa tincidunt dui ut ornare. Mi bibendum neque egestas congue quisque egestas diam in arcu. Sit amet venenatis urna cursus eget nunc scelerisque viverra mauris. Tortor dignissim convallis aenean et tortor at. Nisl pretium fusce id velit ut tortor pretium viverra. Nunc aliquet bibendum enim facilisis. Quis ipsum suspendisse ultrices gravida dictum fusce ut placerat. Dui sapien eget mi proin sed libero. Maecenas sed enim ut sem. Nulla facilisi nullam vehicula ipsum a arcu cursus vitae. Egestas sed sed risus pretium quam. Congue nisi vitae suscipit tellus. Risus viverra adipiscing at in tellus integer. Nisl vel pretium lectus quam id leo in vitae.
          Nisl suscipit adipiscing bibendum est ultricies integer quis auctor. Proin fermentum leo vel orci porta non pulvinar. Sed odio morbi quis commodo. Purus sit amet luctus venenatis lectus. Hac habitasse platea dictumst vestibulum. Consectetur libero id faucibus nisl tincidunt eget nullam non. Habitant morbi tristique senectus et netus et. Nisi vitae suscipit tellus mauris. Tristique sollicitudin nibh sit amet commodo nulla facilisi nullam. Diam vulputate ut pharetra sit amet aliquam id diam.
          Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Pellentesque habitant morbi tristique senectus et netus. Scelerisque fermentum dui faucibus in. Nisi porta lorem mollis aliquam ut porttitor leo. At lectus urna duis convallis convallis. Quis hendrerit dolor magna eget est lorem ipsum dolor. Vel pharetra vel turpis nunc. Ipsum dolor sit amet consectetur. Nam at lectus urna duis convallis convallis tellus. Elementum integer enim neque volutpat ac tincidunt vitae semper. Et ultrices neque ornare aenean euismod elementum nisi. Interdum posuere lorem ipsum dolor sit amet consectetur adipiscing. Mi in nulla posuere sollicitudin aliquam. Tincidunt vitae semper quis lectus nulla at volutpat diam ut. Arcu cursus vitae congue mauris rhoncus aenean vel elit. Ligula ullamcorper malesuada proin libero nunc consequat. Egestas sed tempus urna et. Scelerisque purus semper eget duis at. Ut sem nulla pharetra diam sit amet nisl suscipit.
          Ut eu sem integer vitae. Hendrerit dolor magna eget est. In ornare quam viverra orci sagittis eu volutpat odio facilisis. Ipsum consequat nisl vel pretium lectus. Cras tincidunt lobortis feugiat vivamus. Et molestie ac feugiat sed lectus vestibulum mattis. Augue lacus viverra vitae congue eu consequat. Sit amet volutpat consequat mauris nunc congue nisi vitae suscipit. Dignissim convallis aenean et tortor at risus. Orci porta non pulvinar neque laoreet suspendisse interdum consectetur. Nunc faucibus a pellentesque sit.
          Phasellus faucibus scelerisque eleifend donec pretium vulputate sapien nec. Arcu cursus euismod quis viverra nibh cras pulvinar. Blandit aliquam etiam erat velit scelerisque in dictum. At volutpat diam ut venenatis tellus in. Tempus imperdiet nulla malesuada pellentesque elit eget gravida cum. Lacus laoreet non curabitur gravida. A diam sollicitudin tempor id eu. Sapien et ligula ullamcorper malesuada proin. Fermentum leo vel orci porta non. Nulla posuere sollicitudin aliquam ultrices sagittis orci. Ligula ullamcorper malesuada proin libero nunc consequat. Consectetur adipiscing elit pellentesque habitant morbi. Tortor dignissim convallis aenean et tortor. Nulla facilisi cras fermentum odio eu feugiat. Amet dictum sit amet justo donec enim. Rhoncus mattis rhoncus urna neque viverra justo nec ultrices dui. Arcu cursus euismod quis viverra. Morbi blandit cursus risus at ultrices. Aliquet lectus proin nibh nisl condimentum. Integer vitae justo eget magna fermentum iaculis eu.
          Mattis enim ut tellus elementum sagittis. Pharetra convallis posuere morbi leo. Bibendum arcu vitae elementum curabitur vitae nunc sed velit. Mi tempus imperdiet nulla malesuada pellentesque. Vel facilisis volutpat est velit egestas dui id ornare. Maecenas sed enim ut sem. Eros in cursus turpis massa tincidunt dui ut ornare. Mi bibendum neque egestas congue quisque egestas diam in arcu. Sit amet venenatis urna cursus eget nunc scelerisque viverra mauris. Tortor dignissim convallis aenean et tortor at. Nisl pretium fusce id velit ut tortor pretium viverra. Nunc aliquet bibendum enim facilisis. Quis ipsum suspendisse ultrices gravida dictum fusce ut placerat. Dui sapien eget mi proin sed libero. Maecenas sed enim ut sem. Nulla facilisi nullam vehicula ipsum a arcu cursus vitae. Egestas sed sed risus pretium quam. Congue nisi vitae suscipit tellus. Risus viverra adipiscing at in tellus integer. Nisl vel pretium lectus quam id leo in vitae.
          Nisl suscipit adipiscing bibendum est ultricies integer quis auctor. Proin fermentum leo vel orci porta non pulvinar. Sed odio morbi quis commodo. Purus sit amet luctus venenatis lectus. Hac habitasse platea dictumst vestibulum. Consectetur libero id faucibus nisl tincidunt eget nullam non. Habitant morbi tristique senectus et netus et. Nisi vitae suscipit tellus mauris. Tristique sollicitudin nibh sit amet commodo nulla facilisi nullam. Diam vulputate ut pharetra sit amet aliquam id diam.
          Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Pellentesque habitant morbi tristique senectus et netus. Scelerisque fermentum dui faucibus in. Nisi porta lorem mollis aliquam ut porttitor leo. At lectus urna duis convallis convallis. Quis hendrerit dolor magna eget est lorem ipsum dolor. Vel pharetra vel turpis nunc. Ipsum dolor sit amet consectetur. Nam at lectus urna duis convallis convallis tellus. Elementum integer enim neque volutpat ac tincidunt vitae semper. Et ultrices neque ornare aenean euismod elementum nisi. Interdum posuere lorem ipsum dolor sit amet consectetur adipiscing. Mi in nulla posuere sollicitudin aliquam. Tincidunt vitae semper quis lectus nulla at volutpat diam ut. Arcu cursus vitae congue mauris rhoncus aenean vel elit. Ligula ullamcorper malesuada proin libero nunc consequat. Egestas sed tempus urna et. Scelerisque purus semper eget duis at. Ut sem nulla pharetra diam sit amet nisl suscipit.
          Ut eu sem integer vitae. Hendrerit dolor magna eget est. In ornare quam viverra orci sagittis eu volutpat odio facilisis. Ipsum consequat nisl vel pretium lectus. Cras tincidunt lobortis feugiat vivamus. Et molestie ac feugiat sed lectus vestibulum mattis. Augue lacus viverra vitae congue eu consequat. Sit amet volutpat consequat mauris nunc congue nisi vitae suscipit. Dignissim convallis aenean et tortor at risus. Orci porta non pulvinar neque laoreet suspendisse interdum consectetur. Nunc faucibus a pellentesque sit.
          Phasellus faucibus scelerisque eleifend donec pretium vulputate sapien nec. Arcu cursus euismod quis viverra nibh cras pulvinar. Blandit aliquam etiam erat velit scelerisque in dictum. At volutpat diam ut venenatis tellus in. Tempus imperdiet nulla malesuada pellentesque elit eget gravida cum. Lacus laoreet non curabitur gravida. A diam sollicitudin tempor id eu. Sapien et ligula ullamcorper malesuada proin. Fermentum leo vel orci porta non. Nulla posuere sollicitudin aliquam ultrices sagittis orci. Ligula ullamcorper malesuada proin libero nunc consequat. Consectetur adipiscing elit pellentesque habitant morbi. Tortor dignissim convallis aenean et tortor. Nulla facilisi cras fermentum odio eu feugiat. Amet dictum sit amet justo donec enim. Rhoncus mattis rhoncus urna neque viverra justo nec ultrices dui. Arcu cursus euismod quis viverra. Morbi blandit cursus risus at ultrices. Aliquet lectus proin nibh nisl condimentum. Integer vitae justo eget magna fermentum iaculis eu.
          Mattis enim ut tellus elementum sagittis. Pharetra convallis posuere morbi leo. Bibendum arcu vitae elementum curabitur vitae nunc sed velit. Mi tempus imperdiet nulla malesuada pellentesque. Vel facilisis volutpat est velit egestas dui id ornare. Maecenas sed enim ut sem. Eros in cursus turpis massa tincidunt dui ut ornare. Mi bibendum neque egestas congue quisque egestas diam in arcu. Sit amet venenatis urna cursus eget nunc scelerisque viverra mauris. Tortor dignissim convallis aenean et tortor at. Nisl pretium fusce id velit ut tortor pretium viverra. Nunc aliquet bibendum enim facilisis. Quis ipsum suspendisse ultrices gravida dictum fusce ut placerat. Dui sapien eget mi proin sed libero. Maecenas sed enim ut sem. Nulla facilisi nullam vehicula ipsum a arcu cursus vitae. Egestas sed sed risus pretium quam. Congue nisi vitae suscipit tellus. Risus viverra adipiscing at in tellus integer. Nisl vel pretium lectus quam id leo in vitae.
          Nisl suscipit adipiscing bibendum est ultricies integer quis auctor. Proin fermentum leo vel orci porta non pulvinar. Sed odio morbi quis commodo. Purus sit amet luctus venenatis lectus. Hac habitasse platea dictumst vestibulum. Consectetur libero id faucibus nisl tincidunt eget nullam non. Habitant morbi tristique senectus et netus et. Nisi vitae suscipit tellus mauris. Tristique sollicitudin nibh sit amet commodo nulla facilisi nullam. Diam vulputate ut pharetra sit amet aliquam id diam.
        </Text>
      </Modal>
    </>
  )
};

ReviewTopBar.propTypes = {
  demo: PropTypes.bool,
  stopDemo: PropTypes.func,
  logout: PropTypes.func,
  loadReviews: PropTypes.func,
  submissionQueue: PropTypes.array,
  submissionErrors: PropTypes.array,
};

const styles = StyleSheet.create({
  wrapper: {
    marginBottom: 28
  }
})

export default ReviewTopBar;
